### ISSUE TITLE
Wellcommer is  RBAC or ACL?

### ISSUE THREAD

**Issue by benyang2015** [WellCommerce/WellCommerce#111]
Wellcommer is  RBAC or ACL?

**Comment by adampiotrowski** [comment]
@benyang2015 Neither RBAC nor ACL :)
We're using a stupid-simple functionality to manage the access rights to all admin controller actions. 

All permissions are stored in DB (see user_group_permission table). 

Every user group has its own permission table ie. [http://awesomescreenshot.com/0c5651sxc1](http://awesomescreenshot.com/0c5651sxc1)

Admin routes have an additional option "require_admin_permission" ie.

```
admin.attribute.add:
    path: /admin/attribute/add
    defaults:
        _controller: 'attribute.controller.admin:addAction'
    options:
        require_admin_permission: attribute.add
```
which requires that the user's group has it's enabled to access particular action in controller. 

From my experience, most of shops have the neccesity to give/revoke an access to the whole controller's action (adding, removing, editing) and not per single record/entity.
