### ISSUE TITLE
[Insight] YAML files should not contain syntax error

### ISSUE THREAD

**Issue by adampiotrowski** [WellCommerce/WellCommerce#4]
**[in config/config_dev.yml, line 3](https://github.com/WellCommerce/WellCommerce/blob/master/config/config_dev.yml#L3)**

> Unable to parse at line 3 (near "
").

```
imports:
    - { resource: parameters.yml }

wellcommerce_profiler:
     enabled:  "%profiler%"

wellcommerce_core:
    database:
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/a6f6c588-b8a5-4e82-937e-17ccce617f35/analyses/2)_
