### ISSUE TITLE
WellCommerce support redis or not？

### ISSUE THREAD

**Issue by benyang2015** [WellCommerce/WellCommerce#86]

**Comment by adampiotrowski** [comment]
@benyang2015 Hi, do you mean Redis as a cache storage for Doctrine (metadata cache, query cache, result & second level cache)?

**Comment by benyang2015** [comment]
@adampiotrowski Yes

**Comment by adampiotrowski** [comment]
Redis is now supported by using php-cache adapter.

Switching to Redis requires 3 steps:

1. require cache adapter with composer, follow install instructions here https://github.com/php-cache/redis-adapter 
2. add new cache provider in local config

```
doctrine_cache:
    providers:
        redis:
            type: redis 
```
3. change drivers from doctrine_cache.providers.file_system to doctrine_cache.providers.redis in configuration (ie. locally in wellcommerce.yml) to use new provider

```
orm:
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                query_cache_driver:
                    type: service
                    id: doctrine_cache.providers.file_system
                metadata_cache_driver:
                    type: service
                    id: doctrine_cache.providers.file_system
                result_cache_driver:
                    type: service
                    id: doctrine_cache.providers.file_system
```
